org: mrmclaine
app: shortlinker
service: shortlinker
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: 'node18'
    exclude: ['aws-sdk']
    platform: 'node'
  tableName: 'users-table-${sls:stage}'
  linksTableName: 'links-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - secretsmanager:GetSecretValue
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
            - Fn::GetAtt: [ LinksTable, Arn ]
            - Fn::Sub: "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:my-secret"
        - Effect: Allow
          Action:
            - ses:SendEmail
            - sqs:SendMessage
            - sqs:SendMessageBatch
          Resource: "*"

  environment:
    USERS_TABLE: ${self:custom.tableName}
    LINKS_TABLE: ${self:custom.linksTableName}
    JWT_SECRET_NAME: ${JWT_SECRET_NAME}

functions:
  api:
    handler: dist/index.handler
    events:
      - httpApi: '*'
  registerUser:
    handler: dist/lambdas/register.register
    events:
      - http:
          path: register
          method: post
          cors: true
  loginUser:
    handler: dist/lambdas/login.login
    events:
      - http:
          path: login
          method: post
          cors: true
  createLink:
    handler: dist/lambdas/createLink.createLink
    events:
      - http:
          path: link
          method: post
          cors: true
          authorizer:
            type: TOKEN
            name: jwtAuthorizer
            arn: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:jwtAuthorizer

  getLinkFromShortUrl:
    handler: dist/lambdas/getLinkFromShortUrl.getLinkFromShortUrl
    events:
      - http:
          path: link/{linkId}
          method: get
          cors: true

  deactivateLink:
    handler: dist/lambdas/deactivateLink.deactivateLink
    events:
      - http:
          path: link/{linkId}/deactivate
          method: post
          cors: true
          authorizer:
            type: TOKEN
            name: jwtAuthorizer
            arn: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:jwtAuthorizer

  autoDeactivateExpiredLinks:
    handler: dist/lambdas/cronJob.cronJob
    events:
      - schedule:
          schedule: rate(1 day)

  sendEmail:
    handler: dist/lambdas/sendEmail.sendEmail
    events:
      - sqs:
          arn: arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:EmailQueue
          batchSize: 10

  getLinksByUser:
    handler: dist/lambdas/getLinksByUser.getLinksByUser
    events:
      - http:
          path: links
          method: get
          cors: true
          authorizer:
            type: TOKEN
            name: jwtAuthorizer
            arn: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:jwtAuthorizer

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: "ALL"

    LinksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.linksTableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: linkId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: linkId
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: expiredAt
          Enabled: true
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: "ALL"

    JwtSecret:
      Type: "AWS::SecretsManager::Secret"
      Properties:
        Name: ${JWT_SECRET_NAME}
        Description: "JWT secret for the application"
        GenerateSecretString:
          SecretStringTemplate: '{"jwt":"secret"}'
          GenerateStringKey: "jwt"

    EmailQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "EmailQueue"